# Data Configuration
data_path: "artifacts/train.csv"
preprocessing_path: "models/preprocessing"

# MLflow Configuration
mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  experiment_name: "House Price Predictionn"

# Model Parameters
model_params:
  random_forest_regression:
    n_estimators: 150
    max_depth: 15
    min_samples_split: 2
    random_state: 42
  
  gradient_boosting:
    n_estimators: 150
    learning_rate: 0.1
    max_depth: 5
    random_state: 42
  

# Preprocessing Configuration
categorical_features:
  - 'MSZoning'
  - 'Street'
  - 'LotShape'
  - 'LandContour'
  - 'Utilities'
  - 'LotConfig'
  - 'LandSlope'
  - 'Neighborhood'
  - 'Condition1'
  - 'Condition2'
  - 'BldgType'
  - 'HouseStyle'
  - 'RoofStyle'
  - 'RoofMatl'
  - 'Exterior1st'
  - 'Exterior2nd'
  - 'MasVnrType'
  - 'ExterQual'
  - 'ExterCond'
  - 'Foundation'
  - 'BsmtQual'
  - 'BsmtCond'
  - 'BsmtExposure'
  - 'BsmtFinType1'
  - 'BsmtFinType2'
  - 'Heating'
  - 'HeatingQC'
  - 'CentralAir'
  - 'Electrical'
  - 'KitchenQual'
  - 'Functional'
  - 'GarageType'
  - 'GarageFinish'
  - 'GarageQual'
  - 'GarageCond'
  - 'PavedDrive'
  - 'SaleType'
  - 'SaleCondition'

numerical_features:
  - 'MSSubClass'
  - 'LotFrontage'
  - 'LotArea'
  - 'OverallQual'
  - 'OverallCond'
  - 'YearBuilt'
  - 'YearRemodAdd'
  - 'MasVnrArea'
  - 'BsmtFinSF1'
  - 'BsmtFinSF2'
  - 'BsmtUnfSF'
  - 'TotalBsmtSF'
  - '1stFlrSF'
  - '2ndFlrSF'
  - 'LowQualFinSF'
  - 'GrLivArea'
  - 'BsmtFullBath'
  - 'BsmtHalfBath'
  - 'FullBath'
  - 'HalfBath'
  - 'BedroomAbvGr'
  - 'KitchenAbvGr'
  - 'TotRmsAbvGrd'
  - 'Fireplaces'
  - 'GarageYrBlt'
  - 'GarageCars'
  - 'GarageArea'
  - 'WoodDeckSF'
  - 'OpenPorchSF'
  - 'EnclosedPorch'
  - '3SsnPorch'
  - 'ScreenPorch'
  - 'PoolArea'
  - 'MiscVal'
  - 'MoSold'
  - 'YrSold'